/* Base renderers used only during initial boot before the current English/UX renderers attach.
   Keep this file factual and intentionally minimal so stale design/content assumptions cannot re-enter the wireframe. */

function home(){return `${chrome('/','Home','Boot renderer / current Home is applied by wf-ux-refinement.js')}
<div class="page"><section class="section"><div class="eyebrow">AUX USA</div><h1 class="display h1">Fingertip Tongs</h1><p class="lead">Precise tools for cooking, serving and the table.</p></section></div>${footer()}`}

function shopAll(){return `${chrome('/collections/all','Shop All','商品一覧＋カテゴリ探索')}<div class="page"><section class="section compact"><div class="eyebrow">Shop all</div><h1 class="display h1">All AUX tools.</h1><p class="lead">A focused collection of precision tongs for cooking, serving and the table.</p>${ja('ここではローンチ対象商品の一覧と、COOK / SERVE / TABLEの3カテゴリから探せることを説明する。')}<div class="shop-category-row"><div class="shop-category clickable" data-go="cook"><b>COOK</b><p>Tools for movement, heat and preparation.</p></div><div class="shop-category clickable" data-go="serve"><b>SERVE</b><p>Tools for plating, portioning and sharing.</p></div><div class="shop-category clickable" data-go="table"><b>TABLE</b><p>Tools for smaller tasks at the table.</p></div></div><div class="filterbar"><div>FILTER <span class="tiny">USE / SIZE / FUNCTION</span></div><div>SORT Featured ▾</div></div><div class="grid-products">${Array.from({length:13},(_,i)=>productCard(i)).join('')}</div></section></div>${footer()}`}

function collection(name){return `${chrome('/collections/'+name.toLowerCase(),name,'Boot renderer / current Collection is applied by wf-en-overrides.js')}<div class="page"><section class="section"><div class="eyebrow">Collection</div><h1 class="display h1">${name}</h1><p class="lead">Explore AUX tools designed around this use.</p></section></div>${footer()}`}
