/* Base brand/support renderers. Why AUX is replaced by the current renderer in
   wf-en-detail-overrides.js. Keep boot content neutral and fact-safe. */

function why(){return `${chrome('/pages/why-aux','Why AUX','Boot renderer / current Why AUX renderer loads after navigation setup')}<div class="page"><section class="section"><div class="eyebrow">Why AUX</div><h1 class="display h1">Made with Japanese precision.</h1><p class="lead">AUX designs the contact point, overall form and proportion around the task, supported by Japanese manufacturing quality.</p></section></div>${footer()}`}

function faq(){return `${chrome('/pages/faq','FAQ','購入前後の実務情報')}<div class="page"><section class="section"><div class="support"><div class="eyebrow">Support</div><h1 class="display h1">Frequently asked questions.</h1>${ja('ここでは配送・返品・お手入れ・製造地など、購入前後によく出る質問をまとめて掲載する。')}${['Where do you ship?','How should I care for AUX tongs?','Are the tongs dishwasher safe?','Where are AUX products made?','How do returns work?'].map((q,i)=>`<div class="faq-item"><div class="faq-q"><span>${q}</span><span>＋</span></div>${i===0?'<div class="faq-a">Answer placeholder. Final shipping / returns policy to be confirmed.</div>':''}</div>`).join('')}</div></section></div>${footer()}`}

function info(kind){const map={shipping:['Shipping & Delivery','配送エリア、送料、配送日数、関税・税の扱い'],returns:['Returns / Refunds','返品期限、状態、送料負担、返金方法']};const v=map[kind];return `${chrome('/pages/'+kind,v[0],v[1])}<div class="page"><section class="section"><div class="support"><div class="eyebrow">Support</div><h1 class="display h1">${v[0]}</h1><p class="lead">Clear information for ordering with confidence.</p>${ja(`${v[1]}を、購入前に読みやすい短い項目で整理する。`)}<div class="info-table">${['Policy summary','Conditions','Timing','Exceptions','Contact'].map(x=>`<div class="info-row"><b>${x}</b><span>Final policy copy to be confirmed.</span></div>`).join('')}</div></div></section></div>${footer()}`}

function contact(){return `${chrome('/pages/contact','Contact','シンプルな問い合わせフォーム')}<div class="page"><section class="section"><div class="support"><div class="eyebrow">Contact</div><h1 class="display h1">How can we help?</h1><p class="lead">For product, order and shipping questions.</p>${ja('ここでは商品・注文・配送などの問い合わせ窓口と、必要な入力項目を掲載する。')}<div class="form"><div class="field"><label>Name</label><div class="input"></div></div><div class="field"><label>Email</label><div class="input"></div></div><div class="field full"><label>Topic</label><div class="input"></div></div><div class="field full"><label>Message</label><div class="input textarea"></div></div><div class="field full"><a class="btn black">Send message</a></div></div></div></section></div>${footer()}`}
