const pages={home:{label:'Home',route:'/' ,render:home},shop:{label:'Shop All',route:'/collections/all',render:shopAll},cook:{label:'COOK',route:'/collections/cook',render:()=>collection('COOK')},serve:{label:'SERVE',route:'/collections/serve',render:()=>collection('SERVE')},table:{label:'TABLE',route:'/collections/table',render:()=>collection('TABLE')},pdp:{label:'Product Detail',route:'/products/{handle}',render:pdp},inuse:{label:'In Use',route:'/pages/in-use',render:inUse},why:{label:'Why AUX',route:'/pages/why-aux',render:why},faq:{label:'FAQ',route:'/pages/faq',render:faq},shipping:{label:'Shipping & Delivery',route:'/pages/shipping',render:()=>info('shipping')},returns:{label:'Returns / Refunds',route:'/pages/returns',render:()=>info('returns')},contact:{label:'Contact',route:'/pages/contact',render:contact}};
const nav=[{group:'Core',items:[['home',1]]},{group:'Shop',items:[['shop',1],['cook',2],['serve',2],['table',2],['pdp',2]]},{group:'Discover',items:[['inuse',1]]},{group:'Brand',items:[['why',1]]},{group:'Support',items:[['faq',1],['shipping',1],['returns',1],['contact',1]]}];
let current='home';
const initialParams=new URLSearchParams(location.search);
const initialPage=pages[initialParams.get('page')]?initialParams.get('page'):'home';
function navHTML(){return nav.map((g,gi)=>`<div class="nav-group" data-group="${gi}"><button class="group-btn"><span class="group-label">${g.group}</span><span class="group-chevron">⌄</span></button><div class="subnav">${g.items.map(([id,lvl])=>`<button class="page-link level${lvl}" data-page="${id}" style="${lvl===2?'margin-left:12px;width:calc(100% - 12px)':''}"><span class="dotnav"></span><span class="nav-text">${pages[id].label}<small>${pages[id].route}</small></span></button>`).join('')}</div></div>`).join('')}
function render(id,opts={updateUrl:true}){current=id;document.getElementById('browser').innerHTML=pages[id].render();document.querySelectorAll('.page-link').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.querySelector('.workspace').scrollTop=0;window.scrollTo({top:0,behavior:'instant'});if(opts.updateUrl){const u=new URL(location.href);u.searchParams.set('page',id);u.hash='';history.replaceState(null,'',u);}}
document.getElementById('pageNav').innerHTML=navHTML();
document.getElementById('pageNav').addEventListener('click',e=>{const p=e.target.closest('.page-link');if(p){render(p.dataset.page);return}const g=e.target.closest('.group-btn');if(g)g.parentElement.classList.toggle('closed')});
document.getElementById('browser').addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go&&pages[go.dataset.go]){const target=go.dataset.target;render(go.dataset.go);if(target){const u=new URL(location.href);u.hash=target;history.replaceState(null,'',u);requestAnimationFrame(()=>{const el=document.getElementById(target);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});});}return}const a=e.target.closest('[data-anchor]');if(a){const el=document.getElementById(a.dataset.anchor);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});}});
const app=document.getElementById('app'),layout=document.getElementById('layout');
document.getElementById('metaToggle').onclick=function(){app.classList.toggle('show-meta');this.classList.toggle('active');this.textContent=app.classList.contains('show-meta')?'構成メモを隠す':'構成メモを表示'};
function toggleSide(){layout.classList.toggle('side-collapsed');const c=layout.classList.contains('side-collapsed');document.getElementById('sideToggle').textContent=c?'左メニューを開く':'左メニューを閉じる';document.getElementById('sideIcon').textContent=c?'›':'‹'}
document.getElementById('sideToggle').onclick=toggleSide;document.getElementById('sideIcon').onclick=toggleSide;
render(initialPage,{updateUrl:false});
if(location.hash){requestAnimationFrame(()=>{const el=document.getElementById(location.hash.slice(1));if(el)el.scrollIntoView({behavior:'instant',block:'start'});});}
